### ISSUE TITLE
How to create joint?

### ISSUE THREAD

**Issue by rlj1202** [ByteArena/box2d#6] opened 2018-01-09 07:07 UTC
box2d doc says joint must be created by create method in `B2world`.

```golang
func (world *B2World) CreateJoint(def *B2JointDef) B2JointInterface {
```

But `CreateJoint` method receives `B2JointDef`, not `B2JointDefInterface`.
I cannot pass `*B2PrismaticJointDef` as `*B2JointDef` and even passing `&B2PrismaticJointDef.B2JointDef` will not work because `def.(type)` is `B2JointDef`, not `B2PrismaticJointDef`.
So type asserting will fail.

How can I create various joints?

**Comment by netgusto** [comment] 2018-01-09 09:12
Could you provide a runnable minimal example code please?

**Comment by rlj1202** [comment] 2018-01-09 09:18
```golang
def := box2d.MakeB2PrismaticJointDef()
def.LocalAnchorA = blahblah
def.blahblah = blahblah
// ...

b2joint := b2world.CreateJoint(&def) // will not be compiled
b2joint := b2world.CreateJoint(&def.B2JointDef) // will be compiled but it can't be handled by B2JointCreate because of type assertion
```

**Comment by hcwdikk** [comment] 2018-01-18 18:01
I'm curious about this as well.

**Comment by xtuc** [comment] 2018-01-18 21:14
PR https://github.com/ByteArena/box2d/pull/7

**Comment by hcwdikk** [comment] 2018-01-22 17:23
I'm not sure if this pull request fixes the issue.

```
jointDef := box2d.MakeB2RevoluteJointDef()
jointDef.Initialize(c.body, wheel.body, wheel.body.GetWorldCenter())
jointDef.EnableMotor = false
c.b2World.CreateJoint(&jointDef)
```


This throws B2Assert error. Same goes for using &jointDef.B2JointDef. Am I using it wrong?
@rlj1202

**Comment by rlj1202** [comment] 2018-01-23 08:46
@hcwdikk Uhm... possible cases are [here](https://github.com/ByteArena/box2d/blob/6a120bfe0653a6b77776488137fb5bcf364d27af/DynamicsB2World.go#L279), [here](https://github.com/ByteArena/box2d/blob/6a120bfe0653a6b77776488137fb5bcf364d27af/DynamicsB2Joint.go#L287) and [here](https://github.com/ByteArena/box2d/blob/6a120bfe0653a6b77776488137fb5bcf364d27af/DynamicsB2Joint.go#L354). I cannot see what is wrong with that code.

Did you check whether the b2world is locked or not?

**Comment by hcwdikk** [comment] 2018-01-23 13:29
Okay, I'll try checking if b2world is locked. I didn't know it affects creation of joints.

**Comment by hcwdikk** [comment] 2018-01-23 15:25
Ok I was wrong about b2assert error. My error actually comes from [here](https://github.com/ByteArena/box2d/blob/6a120bfe0653a6b77776488137fb5bcf364d27af/DynamicsB2Joint.go#L380). res.M_edgeA is nil. Since res is initialized on line 368 and M_edgeA  is never set wouldn't it always throw error?

**Comment by rlj1202** [comment] 2018-01-25 10:49
```golang
res.M_edgeA.Joint = nil
res.M_edgeA.Other = nil
res.M_edgeA.Prev = nil
res.M_edgeA.Next = nil

res.M_edgeB.Joint = nil
res.M_edgeB.Other = nil
res.M_edgeB.Prev = nil
res.M_edgeB.Next = nil
```

These initializing codes are actually not necessary. Because golang's variable has default value. For pointer and interface vars, `nil` is default value and for numbers, `0` is default value. So I think those lines has to be removed. And following lines should be added.

```golang
res.M_edgeA = new(B2JointEdge)
res.M_edgeB = new(B2JointEdge)
```

These codes will initialize variables of `M_edgeA` and `M_edgeB` to be `nil`.

**Comment by rlj1202** [comment] 2018-03-16 00:13
Is there no further progress? It is been so long time since I posted this issue. I wish you to give your thoughts about this issue.

**Comment by maxfish** [comment] 2018-08-20 16:44
The changes suggested within this thread have been merged to master. The issue is fixed.

**Closed as completed by maxfish** 2018-08-20 16:44 UTC
